version: '3.1'

services:

  auth-api:
    container_name: auth-application
    image: paz-auth-api
    network_mode: host
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: auth-db
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth-db
